### ISSUE TITLE
Feature Request: patch scope

### ISSUE THREAD

**Issue by PhilippHeuer** [uklance/gradle-java-monkey-patch#2]
Hey,

i want to propose to add a property to the configuration that can be used to control the import scope (only the resources / the classes or both)

In my case i only intend to patch the resources of the dependency into my jar (not the classes).

Thanks in advance

**Comment by uklance** [comment]
I'm not sure I understand what you mean. If you don't want to override any classes simply don't put any files in `src/main/java`

**Comment by PhilippHeuer** [comment]
If i was the author of said dependency that would work, but i have no control over it - therefore i think this is a good way.

Of course i can fork it, remove all classes and publish it myself but i would prefer a configuration option.

**Comment by uklance** [comment]
I still don't understand. The example [here](https://github.com/uklance/gradle-java-monkey-patch/blob/master/spring-patch/build.gradle#L11) monkey patches the `spring-context jar` and I'm certainly not a spring developer. As you can see I only patch a single java file [here](https://github.com/uklance/gradle-java-monkey-patch/blob/master/spring-patch/src/main/java/org/springframework/context/support/ClassPathXmlApplicationContext.java) and everything else will come from the spring jar.

- If you want to patch/change classes in a target jar, put java files in `src/main/java`
- If you want to patch/change resources in a target jar, put files in `src/main/resources`
- For any files you want to remain as is, simply don't include them in `src/main/java` or `src/main/resources` and the files will be sourced from the target jar

There must be something I'm not getting

If you want the resultant jar to be different from the target jar (ie you want the resultant jar to have the classes removed) then I you could configure the `jar` task. But then it's not really a monkey patch because the new jar isn't a drop-in replacement for the old jar. 

Eg to create a jar which only contains resources from the target jar (with overrides from `src/main/resources`):

```groovy
plugins {
    id "com.lazan.java-monkey-patch" version "1.0"
}
monkeyPatch {
    target = 'org.springframework:spring-context:4.3.9.RELEASE'
}
jar {
    exclude '**/*.class'
}
```

As I said, I don't recommend this because your patch jar is now incomplete
